### ISSUE TITLE
chore: add docker-compose (or equivalent) for permify deployment

### ISSUE THREAD

**Issue by seelengxd** [uniconhq/unicon-backend#65]
thoughts on adding a `docker-compose` file to make sure that permify service is online before our backend spins up (in a new PR)? we could use https://github.com/containers/podman-compose to allow compatibility with `podman`

_Originally posted by @shenyih0ng in https://github.com/uniconhq/unicon-backend/pull/57#pullrequestreview-2588503671_

**Comment by shenyih0ng** [comment]
more things we can do:

1. publish our docker image onto `ghcr.io` registry via gh action - this way we get versioning and its easy to rollback if stuff breaks on new releases (as opposed to checking out commits and rebuilding)
2. `podman-auto-update` to update image versions automatically via `systemd` - instead of ssh-ing to our deploy target and running root level deploy scripts we can switch a "pull" via polling strategy + we can get to keep our services up to date (e.g. permify) with latest bug fixes

**Comment by seelengxd** [comment]
- docker image pushed on commit to main --> https://ghcr.io/uniconhq/unicon-backend
- docker-compose file added in unicon vps (using above docker image)
```yaml
services:
  postgres:
    image: docker.io/library/postgres
    environment:
      POSTGRES_USER: <USER>
      POSTGRES_PASSWORD: <PASSWORD>
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
    ports:
      - "5432:5432"
    volumes:
      - ./unicon_pg_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./unicon_mq_data:/var/lib/rabbitmq:Z"
  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: unicon
      MINIO_SECRET_KEY: uniconadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./unicon_minio_data:/data"
    command: server /data --console-address ":9001"
  backend:
    image: ghcr.io/uniconhq/unicon-backend:latest
    pull_policy: always
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: sh
    command: -c "uv run alembic upgrade head && uv run unicon_backend/cli.py permify init && uv run unicon_backend/cli.py permify seed && uv run fastapi run unicon_backend/app.py"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PERMIFY_HOST: ${PERMIFY_HOST}
      RUNNER_URL: ${RUNNER_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      SECRET_KEY: ${SECRET_KEY}
      RABBITMQ_URL: ${RABBITMQ_URL}
  permify:
    image: permify/permify:v1.2.9
    ports:
      - "3476:3476"
      - "3478:3478"
    volumes:
      - "./permify.yaml:/config.yaml"
```
- updated ./deploy.sh to use this
- podman-auto-update
  - ran `sudo systemctl enable --now podman-auto-update.timer`
    - shows up if you run `systemctl list-timers | grep podman-auto-update` but i think i'll have to see it auto update permify to figure out if it is working as expected 
    - maybe reopening once i see it doesnt work
